trigger:
- master
pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: Release
steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    feedsToUse: select
    vstsFeed: my-vsts-feed

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud-Free'
    organization: 'GenericOrg'
    projectKey: 'GenericOrg_uiuxtesting'
    projectName: uiuxtesting
    extraProperties: |
     sonar.host.url=https://sonarcloud.io
     sonar.projectKey=GenericOrg_uiuxtesting
     sonar.organization=GenericOrg

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: dotnet unit test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: dotnet collect code coverage
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code coverage"
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage report
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/**/coverage.cobertura.xml
- task: DotNetCoreCLI@2
  displayName: zipAfterPublish
  inputs:
    command: publish
    publishWebProjects: true
    arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
- task: DotNetCoreCLI@2
  displayName: zipAfterPublish
  inputs:
    command: publish
    publishWebProjects: true
    arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
